<?php

namespace AppBundle\Repository;

/**
 * przystanekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class przystanekRepository extends \Doctrine\ORM\EntityRepository
{
}
